### ISSUE TITLE
Missing elements?

### ISSUE THREAD

**Issue by vr8hub** [b-t-k/eugene-oneill_the-hairy-ape#1]
We're going to ignore that me reviewing one of your books is a little bass-ackwards. :)

The scan has both a dramatic personae (that it calls Characters) and a Scene list. I have seen both of those included in other plays, but I don't know the protocol (the manual doesn't say include or not). Is this a producer case-by-case decision? IOW, did you leave them out on purpose?

**Comment by b-t-k** [comment]
I'll ask.
