### ISSUE TITLE
Song formatting

### ISSUE THREAD

**Issue by vr8hub** [b-t-k/eugene-oneill_the-hairy-ape#3]
1. In the first Paddy song in Scene 1 (starting line 199 in the xhtml file), one issue and an observation/question.
    1. The issue is that the lines are offset in the scan, i.e. the "Whiskey! O Johnny" lines are indented a stop further.
    2. The observation is that putting the two stage directions in its own table entry, and changing the persona, really breaks up the song. The way the scans are, the crowd joins Paddy, but it's still Paddy singing. The way it is in the book, it's the Voices rather than Paddy singing. From a script perspective, I would think those lines need to stay in Paddy's persona. And having the direction inline like it is in the scans keeps the song together.
5. Same line offset issue for the "Far away in Canada" song later in the scene.

**Comment by b-t-k** [comment]
ii. I think you are right. Initially I was thinking that the rest of the song was all in chorus, but in retrospect I believe it is mainly Paddy with  the voices singing the backup.
