### ISSUE TITLE
Thinker

### ISSUE THREAD

**Issue by vr8hub** [b-t-k/eugene-oneill_the-hairy-ape#5]
Rodin's Thinker is quoted at the end of scene 7 in Secretary's directions, "in as near to the attitude of Rodin's "Thinker", but italicized everywhere else. I thought at first it was because it's just "Thinker" instead of _The Thinker_, but in the scene settings in Scene 8, it's just _Thinker_ there as well and it's italicized.

**Comment by b-t-k** [comment]
Oops
